export const videos = [
  {
    id: 1,
    title: "CYBERPUNK | Tudo oque você precisa saber.",
    channel: "Aylon Araújo",
    views: "11 mi de visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb1.png",
  },
  {
    id: 2,
    title: "AVENGERS - THE GAME | Dicas e Truques #02",
    channel: "Aylon Araújo",
    views: "957 mil visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb2.png",
  },
  {
    id: 3,
    title:
      "MULHER DE AMARELO CORRENDO | Você não vai acreditar o motivo que fez ela sair correndo",
    channel: "Aylon Araújo",
    views: "106 mil visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb3.png",
  },
  {
    id: 4,
    title: "A OVELHA NEGRA DA FAMÍLIA | Playboy problemático",
    channel: "Aylon Araújo",
    views: "5,6 mi de visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb4.png",
  },
  {
    id: 5,
    title: 'Rick and "?" | Rick Sanchez demite Morty Smith',
    channel: "Aylon Araújo",
    views: "2,2 mi de visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb5.png",
  },
  {
    id: 6,
    title:
      "ANIQUILADOR DE YOUTUBERS | Floyd Mayweather marca luta com Luccas Neto",
    channel: "Aylon Araújo",
    views: "233 mil visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb6.png",
  },
  {
    id: 7,
    title:
      "TRAILER - POKEMON 2070 | Warner Bros. lança trailer do novo capítulo do longa.",
    channel: "Aylon Araújo",
    views: "118 mil visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb7.png",
  },
  {
    id: 8,
    title: "Surfistas & Furiosos | Vin Diesel é cotado como ator para papel",
    channel: "Aylon Araújo",
    views: "1,9 mi de visualizações",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/thumb8.png",
  },
];
